version: '3'
services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=80

  test:
    build: .
    volumes:
      - ./app:/app
      - ./test:/test  # Mount the test directory
    command: bash -c "python -m unittest discover -s /test"
    depends_on:
      - web